name: CI
on:
  push:
  schedule:
    - cron: '0 13 * * 1'
jobs:         
  build:
    runs-on: ubuntu-latest  
    steps:   
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: benbusby/whoogle-search
          path: whoogle
          ref: main
      
      - name: Get last commit message
        id: last-commit-message
        run: |
          echo "::set-output name=msg::$(git log -1 --pretty=%s)"       
     
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ steps.last-commit-message.outputs.msg }}
